import {
  getCurrentTabId,
  injectCustomJs,
  getStoreKey,
  setStore,
  clearStore,
  sendMessageToContentScript,
  chromeAddListenerMessage,
  sendMessageToExtension,
  createContextMenus,
  createNotifications,
  getChromeUrl,
  commandAddListener,
} from './chrome';
import {
  IsurlExait,
  createRandomCode,
  UUID,
  loadFile,
  image2Base64,
  addEventListener,
  removeEventListener,
  getXPath,
  getELementXpath,
  dispatchEventHandler,
} from './util';

export {
  sendMessageToContentScript,
  getCurrentTabId,
  IsurlExait,
  loadFile,
  createRandomCode,
  UUID,
  injectCustomJs,
  getStoreKey,
  setStore,
  clearStore,
  image2Base64,
  addEventListener,
  removeEventListener,
  chromeAddListenerMessage,
  getXPath,
  getELementXpath,
  dispatchEventHandler,
  sendMessageToExtension,
  createContextMenus,
  createNotifications,
  getChromeUrl,
  commandAddListener,
};
